import React, { Component, useState } from "react";
import Head from "next/head";
import { Box, Stack, IconButton, Grid } from "@mui/material";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
// import MainPage from "./MainPage";
import Image from "next/image";
import MyImage from "../../public/aa.jpg";
import LightModeOutlinedIcon from "@mui/icons-material/LightModeOutlined";
import LightModeIcon from "@mui/icons-material/LightMode";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const toggleDarkMode = () => {
    setDarkMode(!darkMode);
    document.body.classList.toggle("dark-mode");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <main className={styles.main}>
        <Stack direction={"column"}>
          <Box className={styles.first_div}>
            <Box sx={{ position: "relative" }}>
              <Image
                src={MyImage}
                className={styles.proImage}
                alt="Picture of the author"
              />
            </Box>
            <Box className={styles.button_container}>
              <IconButton onClick={toggleDarkMode} aria-label="delete">
                {darkMode ? <LightModeOutlinedIcon /> : <LightModeIcon />}
              </IconButton>
            </Box>
            <Box className={styles.text_container}>
              <h1>my name is turag</h1>
            </Box>
          </Box>
          {/* <Box>
            <h1 >My Name is Turag</h1>
            <style jsx>
              {
                `h1{
                  color:red;
                  font-size:2vw
                }`
              }
            </style>
          </Box> */}
        </Stack>
      </main>
    </>
  );
}
